name: Build
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Test
              run: |
                  yarn test

            - name: Lint
              run: |
                  yarn lint

            - name: Generate docs
              run: |
                  yarn docs
            - name: Upload docs
              uses: actions/upload-artifact@v2
              with:
                  name: docs-files
                  path: ./docs

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: docs-files
                  path: ./docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
