name: Publish Package to npmjs
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
                  # Defaults to the user or organization that owns the workflow file
                  scope: '@octocat'
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: yarn test
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Generate docs
              run: |
                  yarn docs
            - name: Upload docs
              uses: actions/upload-artifact@v2
              with:
                  name: docs-files
                  path: ./docs
    deploy:
        name: Deploy docs
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: docs-files
                  path: ./docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
