name: Publish Package to npmjs
on: push
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Lint
              run: |
                  yarn lint

            - name: Test
              run: |
                  yarn test

            - name: Git config
              run: git config --global user.email "bot@google.com" && git config --global user.name "bot"

            - name: Apply version major
              run: npm version major

            - name: Publish npm version
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Git push version
              run: git push -u origin master --follow-tags

            - name: Generate docs
              run: |
                  yarn docs
            - name: Upload docs
              uses: actions/upload-artifact@v2
              with:
                  name: docs-files
                  path: ./docs
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: docs-files
                  path: ./docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
