name: Publish Package to npmjs
on:
    pull_request:
        branches:
            - master
        types:
            - closed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Test
              run: |
                  yarn test

            - name: Lint
              run: |
                  yarn lint
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    docs:
        name: Deploy docs
        runs-on: ubuntu-latest

        steps:
            - name: Generate docs
              run: |
                  yarn docs
            - name: Upload docs
              uses: actions/upload-artifact@v2
              with:
                  name: docs-files
                  path: ./docs
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: docs-files
                  path: ./docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
