name: Build and test
on: push
jobs:
    test:
        name: Test and lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Lint
              run: |
                  yarn lint

            - name: Test
              run: |
                  yarn test
            - name: Test generate docs
              run: |
                  yarn docs
