name: Build and test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Test
              run: |
                  yarn test

            - name: Lint
              run: |
                  yarn lint
