name: Build and test
on: push
jobs:
    build:
        name: Build and lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install Node, NPM and Yarn
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install modules
              run: |
                  yarn install --frozen-lockfile

            - name: Build
              run: |
                  yarn build

            - name: Lint
              run: |
                  yarn lint
            - name: Test generate docs
              run: |
                  yarn docs
            - name: Upload lib Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: lib
                  path: ./lib
    test-versions:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16, 17, 19, 20, 21, 22]
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: |
                  npm install -g yarn
            - name: Install packages
              run: |
                  yarn install --frozen-lockfile --ignore-engines

            - name: Download lib Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: lib
                  path: ./lib
            - name: Test
              run: yarn test
